alertmanager:
  alertmanagerSpec:
    routePrefix: "/alertmanager"
  enabled: true
  ingress:
    enabled: true
    hosts: []
    paths:
    - "/alertmanager"
crds:
  enabled: false  
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      istio-control-plane-dashboard:
        gnetId: 7645
        revision: 298
      istio-mesh-dashboard:
        gnetId: 7639
        revision: 298
      istio-performance-dashboard:
        gnetId: 11829
        revision: 298
      istio-service-dashboard:
        gnetId: 7636
        revision: 298
      istio-wasm-extension-dashboard:
        gnetId: 13277
        revision: 255
      istio-workload-dashboard:
        gnetId: 7630
        revision: 298
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin
    server:
      root_url: http://{{ include "grafana.fullname" . }}.{{ include "grafana.namespace" . }}.svc.cluster.local/grafana/
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts: []
    path: /grafana
    pathType: Prefix
prometheus:
  ingress:
    enabled: true
    hosts: []
    paths:
    - /prometheus
  prometheusSpec:
    externalUrl: "/prometheus/"
    ignoreNamespaceSelectors: true
    podMonitorSelectorNilUsesHelmValues: false
    routePrefix: "/prometheus/"
    serviceMonitorSelectorNilUsesHelmValues: false